# -*- coding: utf-8 -*-
"""Kopie von pegelbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12iFhQ1XGxSygwIZDaojATGXOtlOWqHbk
"""

import requests
from bs4 import BeautifulSoup

def get_water_level():
    url = 'https://www.pegelonline.wsv.de/gast/stammdaten?pegelnr=9440020'
    headers = {'User-Agent': 'Mozilla/5.0'}

    response = requests.get(url, headers=headers)
    soup = BeautifulSoup(response.text, 'html.parser')

    # Find row containing "Wasserstand [cm]"
    water_level_row = soup.find('td', string='Wasserstand [cm]')
    if water_level_row:
        # Get next cell containing the value
        value_cell = water_level_row.find_next_sibling('td')
        return int(value_cell.text.strip())
    return None

if __name__ == '__main__':
    level = get_water_level()
    if level:
        print(f'Aktueller Wasserstand: {level} cm')
    else:
        print('Wasserstand konnte nicht ausgelesen werden.')